name: Visual Regression Tests

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

env:
  BASE_URL: https://debs-obrien.github.io/playwright-movies-app
  TEST_EMAIL: joedoe@outlook.com
  TEST_PASSWORD: 12345

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Get Playwright version
        id: playwright-version
        run: |
          echo "version=$(node -p "require('./package-lock.json').packages['node_modules/@playwright/test'].version")" >> $GITHUB_OUTPUT

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Verify snapshots exist
        id: check_snapshots
        run: |
          if [ -d "tests" ] && find tests -name "*-snapshots" -type d | grep -q .; then
            echo "snapshots_exist=true" >> $GITHUB_OUTPUT
            echo "Baseline snapshots found"
          else
            echo "snapshots_exist=false" >> $GITHUB_OUTPUT
            echo "No baseline snapshots found"
          fi

      - name: Generate baseline snapshots
        if: steps.check_snapshots.outputs.snapshots_exist == 'false'
        run: |
          echo "Generating baseline snapshots..."
          npx playwright test visual.spec.ts --update-snapshots --workers=4

      - name: Commit baseline snapshots
        if: steps.check_snapshots.outputs.snapshots_exist == 'false'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -f tests/*-snapshots/
          git commit -m "chore: add baseline visual snapshots [skip ci]" || echo "No changes to commit"

      - name: Push baseline snapshots
        if: steps.check_snapshots.outputs.snapshots_exist == 'false' && github.event_name == 'push'
        run: git push

      - name: Run visual regression tests
        if: steps.check_snapshots.outputs.snapshots_exist == 'true'
        run: npx playwright test visual.spec.ts --workers=4

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: |
            test-results/
            TestResults/playwright-report/
            tests/visual.spec.ts-snapshots/**
          retention-days: 30
          